// In your api/supabase/updateWorkforceStatusSB.ts (or rename to insertWorkforceUpdateProfileSB.ts)
import { supabase } from '@/src/lib/supabase'; // Your supabase configuration instance path

export const insertWorkforceUpdateProfileSB = async (applicantData: any, newStatus: string) => {
  const { data, error } = await supabase
    .from('workforce_update_profile')
    .insert([
      {
        id_uin: applicantData.uin || applicantData.id,
        full_name: applicantData.fullName,
        email: applicantData.email,
        emergency_contact_number: applicantData.emergencyContactNo,
        area_of_expertise: applicantData.areaOfExpertise,     // Saved directly as text[]
        preferred_working_area: applicantData.preferredWorkingArea, // Saved directly as text[]
        status: newStatus,
        // created_at will automatically be generated by Supabase if default is timestamptz
      },
    ]);

  if (error) throw error;
  return data;
};